// <auto-generated />
using JasperSiteCore.Models.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace JasperSiteCore.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20180524085226_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("JasperSiteCore.Models.Database.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CategoryId");

                    b.Property<string>("HtmlContent");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<DateTime>("PublishDate");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("JasperSiteCore.Models.Database.BlockHolder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<int>("ThemeId");

                    b.HasKey("Id");

                    b.HasIndex("ThemeId");

                    b.ToTable("BlockHolders");
                });

            modelBuilder.Entity("JasperSiteCore.Models.Database.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("JasperSiteCore.Models.Database.Holder_Block", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BlockHolderId");

                    b.Property<int>("Order");

                    b.Property<int>("TextBlockId");

                    b.HasKey("Id");

                    b.HasIndex("BlockHolderId");

                    b.HasIndex("TextBlockId");

                    b.ToTable("HolderBlocks");
                });

            modelBuilder.Entity("JasperSiteCore.Models.Database.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("JasperSiteCore.Models.Database.Setting", b =>
                {
                    b.Property<string>("Key")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Value");

                    b.HasKey("Key");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("JasperSiteCore.Models.Database.TextBlock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("TextBlocks");
                });

            modelBuilder.Entity("JasperSiteCore.Models.Database.Theme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Themes");
                });

            modelBuilder.Entity("JasperSiteCore.Models.Database.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ArticleId");

                    b.Property<string>("Nickname");

                    b.Property<string>("Password");

                    b.Property<int>("RoleId");

                    b.Property<string>("Salt");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("JasperSiteCore.Models.Database.Article", b =>
                {
                    b.HasOne("JasperSiteCore.Models.Database.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JasperSiteCore.Models.Database.BlockHolder", b =>
                {
                    b.HasOne("JasperSiteCore.Models.Database.Theme", "Theme")
                        .WithMany()
                        .HasForeignKey("ThemeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JasperSiteCore.Models.Database.Holder_Block", b =>
                {
                    b.HasOne("JasperSiteCore.Models.Database.BlockHolder", "BlockHolder")
                        .WithMany()
                        .HasForeignKey("BlockHolderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("JasperSiteCore.Models.Database.TextBlock", "TextBlock")
                        .WithMany()
                        .HasForeignKey("TextBlockId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JasperSiteCore.Models.Database.User", b =>
                {
                    b.HasOne("JasperSiteCore.Models.Database.Article")
                        .WithMany("Users")
                        .HasForeignKey("ArticleId");

                    b.HasOne("JasperSiteCore.Models.Database.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
